SKILLS_DB = [
    "python",
    "java",
    "c",
    "c++",
    "c#",
    "golang",
    "rust",
    "kotlin",
    "swift",
    "r",
    "matlab",
    "sql",
    "mysql",
    "postgresql",
    "mongodb",
    "oracle",
    "sqlite",
    "redis",
    "firebase",
    "machine learning",
    "deep learning",
    "artificial intelligence",
    "data science",
    "data analytics",
    "data analysis",
    "computer vision",
    "nlp",
    "generative ai",
    "llm",
    "transformers",
    "tensorflow",
    "keras",
    "pytorch",
    "scikit-learn",
    "opencv",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "xgboost",
    "lightgbm",
    "huggingface",
    "langchain",
    "fastapi",
    "flask",
    "django",
    "streamlit",
    "gradio",
    "react",
    "node.js",
    "express.js",
    "spring boot",
    "rest api",
    "graphql",
    "docker",
    "kubernetes",
    "jenkins",
    "github actions",
    "ci/cd",
    "aws",
    "azure",
    "gcp",
    "linux",
    "ubuntu",
    "bash",
    "shell scripting",
    "git",
    "github",
    "gitlab",
    "bitbucket",
    "html",
    "css",
    "javascript",
    "typescript",
    "tailwind css",
    "bootstrap",
    "next.js",
    "vue.js",
    "angular",
    "power bi",
    "tableau",
    "excel",
    "spark",
    "hadoop",
    "airflow",
    "etl",
    "data warehouse",
    "big data",
    "cybersecurity",
    "ethical hacking",
    "penetration testing",
    "network security",
    "siem",
    "soc",
    "cryptography",
    "blockchain",
    "solidity",
    "ethereum",
    "web3",
    "unity",
    "unreal engine",
    "blender",
    "game development",
    "arduino",
    "raspberry pi",
    "iot",
    "embedded systems",
    "microcontrollers",
    "robotics",
    "automation",
    "computer networks",
    "operating systems",
    "oop",
    "data structures",
    "algorithms",
    "cloud computing",
    "devops",
    "mlops",
    "api development",
    "software engineering",
    "ui/ux",
    "figma",
    "adobe xd"
]



def extract_skills(text):

    found_skills = []

    text = text.lower()

    for skill in SKILLS_DB:

        if skill.lower() in text:

            found_skills.append(skill)

    return list(set(found_skills))